id: P010488
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1PD105825
  title: ལི་ཁྲིའི་རྟ་རྫོང་།
  author: ''
  volumes:
    9e7887beb2204500bae1ed9a2d45723a:
      image_group_id: I1PD105827
      title: ''
      volume_number: 1
      total_pages: 482
      base_file: v001.txt
